### ISSUE TITLE
Remove DiscordGift.site from the blacklisted URLs.

### ISSUE THREAD

**Issue by Iinksafe** [DrNoSleep/scamlinks#2]
Hi there!

I am an administrator of the DiscordGift.site server. **DiscordGift.site is a rick rolling site, designed for Discord users to rick roll their friends.**
I kindly ask a maintainer of this project, please remove that URL from the list-discord.txt file (as said before, it's safe). Thank you!

Kind regards,
Link

**Comment by DrNoSleep** [comment]
Hey there link,
I have removed DiscordGift.site from the list of scam domains.
Thank you for informing me it is safe and just used as a little troll.

- DrNoSleep
